//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillMaker.DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int SaleId { get; set; }
        public int UnitId { get; set; }
        public decimal Quantity { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }

        public decimal TotalTaxCalculatedPrice { get; set; }

        public decimal MRP { get { return Sale.SellType ? Product.SellPrice : Product.BuyPrice; } }
        public decimal TotalSgstPrice { get; set; }

        public decimal TotalCgstPrice { get; set; }

        public void Calculate()
        {
            decimal productBasePrice = Sale.SellType == true ? Product.SellPrice : Product.BuyPrice;
            productBasePrice = productBasePrice / (1 + (Product.Cgst + Product.Sgst) / 100);
            TotalTaxCalculatedPrice = productBasePrice * Quantity * MeasureUnit.Conversion;
            TotalCgstPrice = TotalTaxCalculatedPrice * Product.Cgst / 100;
            TotalSgstPrice = TotalTaxCalculatedPrice * Product.Sgst / 100;
        }
    }
}
