//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillMaker.DataConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLog
    {
        public int Id { get; set; }
        public int ProductUnitId { get; set; }
        public decimal AddedValue { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual ProductUnit ProductUnit { get; set; }
    }
}
