//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillMaker.DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AcoountNo { get; set; }
        public decimal Balance { get; set; }
        public string IFSCCode { get; set; }
    }
}
