//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillMaker.DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionProperty
    {
        public int Id { get; set; }
        public int TransactionId { get; set; }
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
