//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillMaker.DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int UnitId { get; set; }
        public decimal ValueAdded { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int PersonId { get; set; }
        public bool VoucherType { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
        public virtual Person Person { get; set; }
    }
}
